# Generated by Django 3.1.1 on 2021-02-05 19:03

from django.db import migrations, models
import django.db.models.deletion
import partserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the line(s)', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the part's name", max_length=50)),
                ('number', models.CharField(help_text="Enter the part's number", max_length=10)),
                ('quantity', models.PositiveIntegerField(blank=True, help_text="Part's in stock quantity")),
                ('specs', models.TextField(help_text='Enter the specification of the part', max_length=1000)),
                ('lines', models.ForeignKey(help_text='Select the applied lines for the part', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partserver.line')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the section for the line', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PartImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=partserver.models.get_image_filename, verbose_name='images')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partserver.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='section',
            field=models.ForeignKey(help_text='Select the section(s) for this part', on_delete=django.db.models.deletion.CASCADE, to='partserver.section'),
        ),
        migrations.AddField(
            model_name='line',
            name='section',
            field=models.ManyToManyField(help_text='Select the section(s) for this line', to='partserver.Section'),
        ),
    ]
