# Generated by Django 3.1.1 on 2021-02-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text="Part's in stock quantity", null=True),
        ),
    ]
