# Generated by Django 3.1.1 on 2021-02-12 17:34

from django.db import migrations, models
import django.db.models.deletion
import partserver.models
import partserver.validators


class Migration(migrations.Migration):

    dependencies = [
        ('partserver', '0002_auto_20210205_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text="Enter the part's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.CharField(help_text="Enter the part's number", max_length=20),
        ),
        migrations.CreateModel(
            name='Schematic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the schematic's name", max_length=100)),
                ('pdfFile', models.FileField(upload_to=partserver.models.get_schematic_filename, validators=[partserver.validators.validate_file_extension])),
                ('line', models.ForeignKey(help_text='Select the applied line for the schematic', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partserver.line')),
                ('section', models.ForeignKey(help_text='Select the section for the schematic', on_delete=django.db.models.deletion.CASCADE, to='partserver.section')),
            ],
        ),
    ]
