# Generated by Django 3.1.1 on 2021-02-26 13:43

from django.db import migrations, models
import django.db.models.deletion
import partserver.models
import partserver.validators


class Migration(migrations.Migration):

    dependencies = [
        ('partserver', '0003_auto_20210212_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the manual's name", max_length=100)),
                ('pdfFile', models.FileField(upload_to=partserver.models.get_manual_filename, validators=[partserver.validators.validate_file_extension])),
                ('line', models.ForeignKey(help_text='Select the applied line for the manual', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partserver.line')),
                ('section', models.ForeignKey(help_text='Select the section for the manual', on_delete=django.db.models.deletion.CASCADE, to='partserver.section')),
            ],
        ),
    ]
